import type { Listing } from './types'

export const mockListings: Listing[] = [
  {
    id: '1',
    title: 'HDPE Plastic Scraps',
    category: 'plastics',
    tag: 'Polymer',
    tagColor: 'polymer',
    distanceKm: 12,
    quantity: '5.2 Tons',
    price: '$420 / ton',
    company: 'EcoPlast Ind.',
    image:
      'https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=800&h=500&fit=crop',
    images: [
      'https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=800&h=500&fit=crop',
      'https://images.unsplash.com/photo-1532996122724-e3c354a0b16b?w=800&h=500&fit=crop',
      'https://images.unsplash.com/photo-1581092160562-40aa08e78837?w=800&h=500&fit=crop',
      'https://images.unsplash.com/photo-1611273426858-450d8b3c702d?w=800&h=500&fit=crop',
    ],
    aiVerified: true,
    breadcrumb: ['Marketplace', 'Raw Materials', 'Polymers', 'HDPE Plastic Scraps'],
    location: 'Rotterdam, NL',
    pricePerUnit: '$420.00 / Metric Ton',
    minOrder: '2 Metric Tons',
    availableAmount: 52,
    availableUnit: 'MT',
    shippingTerms: 'EXW (Ex Works)',
    leadTime: 'Ready for Dispatch (3–5 business days)',
    origin: 'Rotterdam, NL',
    specs: [
      { label: 'Material Type', value: 'HDPE' },
      { label: 'Purity Grade', value: '98.2%', highlight: true },
      { label: 'Form', value: 'Flakes / Regrind' },
      { label: 'Color', value: 'Natural / Mixed' },
      { label: 'Moisture Content', value: '< 0.5%' },
      { label: 'Melt Flow Index', value: '0.4 – 0.8 g/10min' },
      { label: 'Contamination', value: 'PVC < 100ppm' },
      { label: 'Packaging', value: 'Big Bags (1 MT)' },
    ],
    aiSummary:
      'This batch shows consistent melt flow and low moisture based on uploaded lab reports. Minor color variation is within acceptable limits for non-food-grade reprocessing. Recommended for pipe extrusion and blow molding applications.',
    seller: {
      name: 'EcoPlast Ind.',
      location: 'Rotterdam, Netherlands',
      rating: 4.7,
      reviewCount: 86,
      reliabilityScore: 96,
      responseTime: '< 3 hrs',
    },
    similar: [
      {
        id: '6',
        title: 'Cotton Fabric Offcuts',
        location: 'Berlin, DE',
        price: '$0.35 / kg',
        purity: '92% Purity',
        status: 'Bulk',
        image:
          'https://images.unsplash.com/photo-1558171813-4c088753af8f?w=400&h=280&fit=crop',
      },
      {
        id: '2',
        title: 'Aluminum Offcuts',
        location: 'Munich, DE',
        price: '$1.8 / kg',
        purity: '99% Purity',
        status: 'Verified',
        image:
          'https://images.unsplash.com/photo-1504328345606-18bbc8c9d7d1?w=400&h=280&fit=crop',
      },
    ],
  },
  {
    id: '2',
    title: 'Aluminum Offcuts',
    category: 'metals',
    tag: 'Metal',
    tagColor: 'metal',
    distanceKm: 8,
    quantity: '1200 kg',
    price: '$1.8 / kg',
    company: 'MetalWorks GmbH',
    image:
      'https://images.unsplash.com/photo-1504328345606-18bbc8c9d7d1?w=800&h=500&fit=crop',
    images: [
      'https://images.unsplash.com/photo-1504328345606-18bbc8c9d7d1?w=800&h=500&fit=crop',
      'https://images.unsplash.com/photo-1565193566171-7a0ee8dbe628?w=800&h=500&fit=crop',
      'https://images.unsplash.com/photo-1581094794329-cd2c90f5b3b2?w=800&h=500&fit=crop',
    ],
    aiVerified: true,
    breadcrumb: ['Marketplace', 'Raw Materials', 'Metals', 'Aluminum Offcuts'],
    location: 'Munich, DE',
    pricePerUnit: '$1.80 / kg',
    minOrder: '200 kg',
    availableAmount: 1200,
    availableUnit: 'kg',
    shippingTerms: 'FCA (Free Carrier)',
    leadTime: 'Ready for Dispatch (1–2 business days)',
    origin: 'Munich, DE',
    specs: [
      { label: 'Material Type', value: 'Aluminum 6061' },
      { label: 'Purity Grade', value: '99.1%', highlight: true },
      { label: 'Form', value: 'Offcuts / Sheets' },
      { label: 'Thickness', value: '2 – 8 mm' },
      { label: 'Surface', value: 'Mill finish' },
      { label: 'Contamination', value: 'Oil residue < 0.1%' },
      { label: 'Packaging', value: 'Palletized bundles' },
      { label: 'Certification', value: 'Mill test cert available' },
    ],
    aiSummary:
      'High-grade aluminum offcuts suitable for remelting or direct CNC reuse. Spectrometer analysis confirms 6061 alloy composition with minimal iron contamination. Ideal for automotive and aerospace secondary processing.',
    seller: {
      name: 'MetalWorks GmbH',
      location: 'Munich, Germany',
      rating: 4.9,
      reviewCount: 124,
      reliabilityScore: 98,
      responseTime: '< 2 hrs',
    },
    similar: [
      {
        id: '1',
        title: 'HDPE Plastic Scraps',
        location: 'Rotterdam, NL',
        price: '$420 / ton',
        purity: '98% Purity',
        status: 'Verified',
        image:
          'https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=400&h=280&fit=crop',
      },
      {
        id: '5',
        title: 'Broken Wood Pallets',
        location: 'Hamburg, DE',
        price: 'Free',
        purity: '85% Purity',
        status: 'Bulk',
        image:
          'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&h=280&fit=crop',
      },
    ],
  },
  {
    id: '3',
    title: 'Spent Sulfuric Acid',
    category: 'chemicals',
    tag: 'Chemical',
    tagColor: 'chemical',
    distanceKm: 24,
    quantity: '500 Gallons',
    price: 'Negotiable',
    company: 'ChemCycle Ltd.',
    image:
      'https://images.unsplash.com/photo-1532187863486-abf9dbad1b69?w=800&h=500&fit=crop',
    images: [
      'https://images.unsplash.com/photo-1532187863486-abf9dbad1b69?w=800&h=500&fit=crop',
      'https://images.unsplash.com/photo-1582719471384-894fbb16e074?w=800&h=500&fit=crop',
    ],
    aiVerified: true,
    breadcrumb: ['Marketplace', 'Chemicals', 'Acids', 'Spent Sulfuric Acid'],
    location: 'Antwerp, BE',
    pricePerUnit: 'Negotiable',
    minOrder: '100 Gallons',
    availableAmount: 500,
    availableUnit: 'Gallons',
    shippingTerms: 'EXW (Ex Works)',
    leadTime: 'Scheduled pickup (5–7 business days)',
    origin: 'Antwerp, BE',
    specs: [
      { label: 'Chemical Type', value: 'H₂SO₄ (spent)' },
      { label: 'Concentration', value: '45 – 55%', highlight: true },
      { label: 'pH', value: '< 1' },
      { label: 'Heavy Metals', value: 'Below EU limits' },
      { label: 'Container', value: 'HDPE IBC totes' },
      { label: 'SDS Available', value: 'Yes' },
      { label: 'Regulatory', value: 'ADR Class 8' },
      { label: 'Reuse Application', value: 'Neutralization / recovery' },
    ],
    aiSummary:
      'Spent acid batch suitable for neutralization or metal recovery processes. Lab analysis confirms concentration within stated range. Proper hazmat handling and transport documentation required per EU ADR regulations.',
    seller: {
      name: 'ChemCycle Ltd.',
      location: 'Antwerp, Belgium',
      rating: 4.5,
      reviewCount: 42,
      reliabilityScore: 94,
      responseTime: '< 4 hrs',
    },
    similar: [
      {
        id: '4',
        title: 'OCC Paper Bales',
        location: 'Brussels, BE',
        price: '$95 / ton',
        purity: '94% Purity',
        status: 'Bulk',
        image:
          'https://images.unsplash.com/photo-1610557892470-55d9e80c0bce?w=400&h=280&fit=crop',
      },
    ],
  },
  {
    id: '4',
    title: 'OCC Paper Bales',
    category: 'organic',
    tag: 'Paper',
    tagColor: 'paper',
    distanceKm: 5,
    quantity: '15 Tons',
    price: '$95 / ton',
    company: 'GreenFiber Co.',
    image:
      'https://images.unsplash.com/photo-1610557892470-55d9e80c0bce?w=800&h=500&fit=crop',
    images: [
      'https://images.unsplash.com/photo-1610557892470-55d9e80c0bce?w=800&h=500&fit=crop',
      'https://images.unsplash.com/photo-1532996122724-e3c354a0b16b?w=800&h=500&fit=crop',
    ],
    aiVerified: true,
    breadcrumb: ['Marketplace', 'Organic Waste', 'Paper', 'OCC Paper Bales'],
    location: 'Brussels, BE',
    pricePerUnit: '$95.00 / Metric Ton',
    minOrder: '5 Metric Tons',
    availableAmount: 15,
    availableUnit: 'MT',
    shippingTerms: 'DAP (Delivered at Place)',
    leadTime: 'Ready for Dispatch (2–4 business days)',
    origin: 'Brussels, BE',
    specs: [
      { label: 'Material Type', value: 'OCC (Old Corrugated)' },
      { label: 'Purity Grade', value: '94.5%', highlight: true },
      { label: 'Moisture Content', value: '< 12%' },
      { label: 'Bale Weight', value: '~1.1 MT each' },
      { label: 'Contamination', value: 'Plastic < 2%' },
      { label: 'Grade', value: 'ISRI Grade 11' },
      { label: 'Storage', value: 'Covered warehouse' },
      { label: 'Certification', value: 'FSC chain of custody' },
    ],
    aiSummary:
      'Well-sorted OCC bales with low plastic contamination. Moisture levels are within industry standard for pulping operations. Consistent bale density supports efficient transport planning.',
    seller: {
      name: 'GreenFiber Co.',
      location: 'Brussels, Belgium',
      rating: 4.6,
      reviewCount: 67,
      reliabilityScore: 95,
      responseTime: '< 2 hrs',
    },
    similar: [
      {
        id: '5',
        title: 'Broken Wood Pallets',
        location: 'Hamburg, DE',
        price: 'Free',
        purity: '85% Purity',
        status: 'Bulk',
        image:
          'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&h=280&fit=crop',
      },
    ],
  },
  {
    id: '5',
    title: 'Broken Wood Pallets',
    category: 'organic',
    tag: 'Wood',
    tagColor: 'wood',
    distanceKm: 18,
    quantity: '400 Units',
    price: 'Free',
    company: 'LogiPack Solutions',
    image:
      'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&h=500&fit=crop',
    images: [
      'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&h=500&fit=crop',
      'https://images.unsplash.com/photo-1595846519845-68e298c2edd8?w=800&h=500&fit=crop',
    ],
    aiVerified: false,
    breadcrumb: ['Marketplace', 'Organic Waste', 'Wood', 'Broken Wood Pallets'],
    location: 'Hamburg, DE',
    pricePerUnit: 'Free (pickup only)',
    minOrder: '50 Units',
    availableAmount: 400,
    availableUnit: 'Units',
    shippingTerms: 'EXW (Self pickup)',
    leadTime: 'Available immediately',
    origin: 'Hamburg, DE',
    specs: [
      { label: 'Material Type', value: 'Euro pallets (EPAL)' },
      { label: 'Condition', value: 'Broken / repairable' },
      { label: 'Wood Type', value: 'Pine / spruce mix' },
      { label: 'Treatment', value: 'Heat-treated (HT)' },
      { label: 'Nail Content', value: 'Standard ring shank' },
      { label: 'Dimensions', value: '1200 × 800 mm' },
      { label: 'Estimated Reuse', value: '60 – 70%', highlight: true },
      { label: 'Pickup Hours', value: 'Mon–Fri 08:00–17:00' },
    ],
    aiSummary:
      'Mixed lot of broken EPAL pallets suitable for repair, chipboard feedstock, or biomass fuel. Visual inspection suggests majority are repairable with standard pallet components. Free disposal for buyer — logistics cost only.',
    seller: {
      name: 'LogiPack Solutions',
      location: 'Hamburg, Germany',
      rating: 4.3,
      reviewCount: 31,
      reliabilityScore: 91,
      responseTime: '< 6 hrs',
    },
    similar: [
      {
        id: '4',
        title: 'OCC Paper Bales',
        location: 'Brussels, BE',
        price: '$95 / ton',
        purity: '94% Purity',
        status: 'Verified',
        image:
          'https://images.unsplash.com/photo-1610557892470-55d9e80c0bce?w=400&h=280&fit=crop',
      },
    ],
  },
  {
    id: '6',
    title: 'Cotton Fabric Offcuts',
    category: 'textiles',
    tag: 'Textile',
    tagColor: 'textile',
    distanceKm: 31,
    quantity: '850 kg',
    price: '$0.35 / kg',
    company: 'TextileLoop AG',
    image:
      'https://images.unsplash.com/photo-1558171813-4c088753af8f?w=800&h=500&fit=crop',
    images: [
      'https://images.unsplash.com/photo-1558171813-4c088753af8f?w=800&h=500&fit=crop',
      'https://images.unsplash.com/photo-1558171813-4c088753af8f?w=800&h=500&fit=crop',
    ],
    aiVerified: true,
    breadcrumb: ['Marketplace', 'Textiles', 'Cotton', 'Cotton Fabric Offcuts'],
    location: 'Berlin, DE',
    pricePerUnit: '$0.35 / kg',
    minOrder: '100 kg',
    availableAmount: 850,
    availableUnit: 'kg',
    shippingTerms: 'EXW (Ex Works)',
    leadTime: 'Ready for Dispatch (3–5 business days)',
    origin: 'Berlin, DE',
    specs: [
      { label: 'Material Type', value: '100% Cotton' },
      { label: 'Purity Grade', value: '92.0%', highlight: true },
      { label: 'Form', value: 'Offcuts / scraps' },
      { label: 'Color Mix', value: 'White / natural dominant' },
      { label: 'Average Size', value: '15 × 20 cm pieces' },
      { label: 'Contamination', value: 'Synthetic < 5%' },
      { label: 'Packaging', value: 'Compressed bales' },
      { label: 'End Use', value: 'Insulation / stuffing / rags' },
    ],
    aiSummary:
      'Clean cotton offcuts from garment manufacturing with low synthetic contamination. Fiber length is suitable for mechanical recycling into non-woven products or industrial wiping cloths.',
    seller: {
      name: 'TextileLoop AG',
      location: 'Berlin, Germany',
      rating: 4.8,
      reviewCount: 53,
      reliabilityScore: 97,
      responseTime: '< 2 hrs',
    },
    similar: [
      {
        id: '1',
        title: 'HDPE Plastic Scraps',
        location: 'Rotterdam, NL',
        price: '$420 / ton',
        purity: '98% Purity',
        status: 'Verified',
        image:
          'https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=400&h=280&fit=crop',
      },
    ],
  },
]

export function getListingById(id: string): Listing | undefined {
  return mockListings.find((l) => l.id === id)
}
